name: music_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pull_to_refresh: ^1.5.8
  toast: ^0.1.5
  flutter_spinkit: ^4.1.2+1
  carousel_slider: ^2.1.0
  provider: ^4.1.2
  graphql: ^3.0.2
  shared_preferences: ^0.5.7+3
  logger: ^0.9.1
  responsive_grid: ^1.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/splash.png
   - assets/images/splash_three.png
   - assets/images/splash_tow.png
   - assets/images/right.png
   - assets/images/menu.png
   - assets/images/share.png
   - assets/images/play.png
   - assets/images/bg_image.png
   - assets/images/t_1.png
   - assets/images/t_2.png
   - assets/images/t_3.png
   - assets/images/top_1.png
   - assets/images/top_2.png
   - assets/images/top_3.png
   - assets/images/bell.png
   - assets/images/discover.png
   - assets/images/home.png
   - assets/images/radio.png
   - assets/images/tv.png
   - assets/images/avatar.png
   - assets/images/crown.png
   - assets/images/album.png
   - assets/images/artists.png
   - assets/images/avatar.png
   - assets/images/crown.png
   - assets/images/downloaded_items.png
   - assets/images/fav.png
   - assets/images/local_files.png
   - assets/images/recent_history.png
   - assets/images/soungs.png
   - assets/images/youtube.png
   - assets/images/exit.png
   - assets/images/backword.png
   - assets/images/bg.png
   - assets/images/download_item.png
   - assets/images/forward.png
   - assets/images/left.png
   - assets/images/loading.png
   - assets/images/louder.png
   - assets/images/mask_group.png
   - assets/images/options.png
   - assets/images/puse.png
   - assets/images/mock_images/

#    - images/a_dot_burr.jpeg
#    - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
